# This scenario is templated with YTE (https://yte-template-engine.github.io)
# and rendered for each group (see sample sheet).
# A variable `samples` is available, holding the dataframe of
# the sample sheet, filtered to those samples contained in the group to be rendered.
# For example, this can be used to pass arbitrary column values (like the purity below),
# to the sample definitions.
# Note that sample names here must correspond to the alias column in the sample sheet.
# In addition, a variable `group_annotation` is available, which holds the row of the group
# from the group annotation table (if specified in the config) as a pandas Series.

#example working config for hla typing.

__definitions__:
  - samples = params.samples
  - |
    def contamination(alias):
      return 1.0 - samples.loc[samples["alias"] == alias, "purity"].squeeze()
  - sex = params.annotation["sex"]
  - has_biopsy = (samples["alias"] == "tumor_biopsy").any()
  - resection_aliases = samples.loc[samples["alias"].str.startswith("tumor_resection"), "alias"]
  - n_resection_aliases = len(resection_aliases)

species:
  heterozygosity: 0.001
  ploidy:
    male:
      all: 2
      X: 1
      Y: 1
    female:
      all: 2
      X: 2
      Y: 0

samples:
  normal:
    resolution: 0.1
    sex: ?sex
    somatic-effective-mutation-rate: 1e-6
  ?for ralias in resection_aliases:
    ?ralias:
      resolution: 0.01
      sex: ?sex
      somatic-effective-mutation-rate: 1e-6
      inheritance:
        ?if has_biopsy:
          subclonal:
            from: tumor_biopsy
        ?else:
          clonal:
            from: normal
            somatic: true
      ?if contamination(ralias) > 0.0:
        contamination:
          by: normal
          fraction: ?float(contamination(ralias))
  ?if has_biopsy:
    tumor_biopsy:
      resolution: 0.01
      sex: ?sex
      somatic-effective-mutation-rate: 1e-6
      inheritance:
        clonal:
          from: normal
          somatic: true
      ?if contamination("tumor_biopsy") > 0.0:
        contamination:
          by: normal
          fraction: ?float(contamination('tumor_biopsy'))

events:
  ?if n_resection_aliases > 0 and has_biopsy:
    somatic_tumor: "normal:0.0 & tumor_biopsy:]0.0,1.0]"
    somatic_resection: "normal:0.0 & tumor_biopsy:0.0 & tumor_resection:]0.0,1.0]"
  ?elif n_resection_aliases > 0:
    somatic_resection: "normal:0.0 & tumor_resection:]0.0,1.0]"
  ?elif has_biopsy:
    somatic_tumor: "normal:0.0 & tumor_biopsy:]0.0,1.0]"
  germline: "normal:0.5 | normal:1.0"
  somatic_normal: "normal:]0.0,0.5["