__use_yte__: true

name: ?f"Fusion calls {wildcards.event}"

default-view: ?f"{params.groups[0]}-fusions"

__definitions__:
  - import os
  - |
    def read_file(path):
        return open(path, 'r').read()

datasets:
  ?for group, path in zip(params.groups, input.fusion_calls):
    ?f"{group}-fusions":
      path: ?path
      separator: "\t"

views:
  ?for group in params.groups:
    ?f"{group}-fusions":
          desc: ?f"Fusion calls"
          dataset: ?f"{group}-fusions"
          render-table:
            add-columns:
              breakpoint 1:
                value: function create_position(row) { return ":".join([row.chromosome_partner1, row.position_partner1]) }
                link-to-url:
                  ensembl:
                    url: ?f"https://www.ensembl.org/{params.species}/Gene/Summary?g={{value}}"
            columns:
              feature_id_partner1:
                label: HUGO gene name breakpoint 1
                link-to-url:
                  gene_card:
                    url: "https://www.genecards.org/cgi-bin/carddisp.pl?gene={value}"
              exon_partner1:
                label: exon breakpoint 1
              site1:
                label: site breakpoint 1
                plot:
                  heatmap:
                    type: nominal
                    color-scheme: set1
                    aux-domain-columns:
                      - site2
              feature_name_partner1:
                label: ensembl ID breakpoint 1
                display-mode: detail
                link-to-url:
                  ensembl:
                    url: ?f"https://www.ensembl.org/{params.species}/Gene/Summary?g={{value}}"
              feature_name_partner2:
                label: ensembl ID breakpoint 2
                display-mode: detail
                link-to-url:
                  ensembl:
                    url: ?f"https://www.ensembl.org/{params.species}/Gene/Summary?g={{value}}"
            add-columns:
              breakpoint 2:
                value: function create_position(row) { return ":".join([row.chromosome_partner2, row.position_partner2]) }
                link-to-url:
                  ensembl:
                    url: ?f"https://www.ensembl.org/{params.species}/Location/View?r={{value}}"
            columns:
              feature_id_partner2:
                label: HUGO gene name breakpoint 2
                link-to-url:
                  gene_card:
                    url: "https://www.genecards.org/cgi-bin/carddisp.pl?gene={value}"
              exon_partner2:
                label: exon breakpoint 2
              site2:
                label: site breakpoint 2
                plot:
                  heatmap:
                    type: nominal
                    color-scheme: set1
                    aux-domain-columns:
                      - site1
              type:
                plot:
                  heatmap:
                    type: nominal
                    color-scheme: category10
              reading_frame:
                  heatmap:
                    type: nominal
                    color-scheme: dark2
              "regex('.+: allele frequency')":
                plot: 
                  ticks:
                    scale: "linear"
                    domain: [0.0, 1.0]
                    aux-domain-columns:
                      - "regex('.+: allele frequency')"
              "regex('.+: read depth')":
                plot: 
                  ticks:
                    scale: "linear"
                    aux-domain-columns:
                      - "regex('.+: read depth')"
              "regex('prob: .+')":
                plot:
                  heatmap:
                    scale: linear
                    domain: [0.0, 1.0]
                    range:
                      - white
                      - "#1f77b4"
              ?for alias in params.samples.loc[params.samples["group"] == group, "alias"]:
                '?f"{alias}: short observations"':
                  optional: true
                  custom-plot:
                    data: ?read_file(input.data_short_observations)
                    spec: ?read_file(input.spec_short_observations)
                  display-mode: detail
                '?f"{alias}: observations"':
                  optional: true
                  custom-plot:
                    data: ?read_file(input.data_observations)
                    spec-path: ?input.spec_observations
                  display-mode: detail