name: ?f"Variant calls {wildcards.event}"

datasets:
  ?for group, path in zip(params.groups, params.coding_calls):
    ?f"{group}-coding":
      path: ?path
      separator: "\t"
  ?for group, path in zip(params.groups, params.noncoding_calls):
    ?f"{group}-noncoding":
      path: ?path
      separator: "\t"
  ?for group, path in zip(params.groups, params.coding_plotdata):
    ?f"{group}-coding-plotdata":
      path: ?path
      separator: "\t"
  ?for group, path in zip(params.groups, params.noncoding_plotdata):
    ?f"{group}-noncoding-plotdata":
      path: ?path
      separator: "\t"

views:
  ?for group in params.groups:
    ?f"{group}-coding":
      desc: ?f"Variants in coding regions.\n{config['calling']['fdr-control']['events'][wildcards.event]['desc']}"
      dataset: ?f"{group}-coding"
      render-table:
        symbol:
          custom: |
            function(value, row) {
              return `<a href="https://www.ensembl.org/Multi/Search/Results?q=${row['feature']}" target="_blank">${value}</a>`
            }
        impact:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        consequence:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category20

    ?f"{group}-noncoding":
      desc: ?f"Variants in non-coding regions.\n{config['calling']['fdr-control']['events'][wildcards.event]['desc']}"
      dataset: ?f"{group}-noncoding"
      render-table:
        symbol:
          custom: |
            function(value, row) {
              return `<a href="https://www.ensembl.org/Multi/Search/Results?q=${row['feature']}" target="_blank">${value}</a>`
            }
        impact:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category10
        consequence:
          plot:
            heatmap:
              scale: ordinal
              color-scheme: category20

  ?for group, plot_spec in zip(params.groups, params.plot_specs):
    ?for impact in ["coding", "noncoding"]:
      ?f"{group}-{impact}-plot:
        dataset: ?f"{group}-{impact}-plotdata"
        render-plot:
          spec-path: ?plot_spec