name: ?f"Variant calls {wildcards.event}"

__definitions__:
  - |
    def read_file(path):
        return open(path, 'r').read()

datasets:
  ?for group, path in zip(params.groups, params.coding_calls):
    ?f"{group}-coding":
      path: ?path
      separator: "\t"
  ?for group, path in zip(params.groups, params.noncoding_calls):
    ?f"{group}-noncoding":
      path: ?path
      separator: "\t"

views:
  ?for group in params.groups:
    ?f"{group}-coding":
      desc: ?f"Variants in coding regions.\n{config['calling']['fdr-control']['events'][wildcards.event]['desc']}"
      dataset: ?f"{group}-coding"
      render-table:
        symbol:
          link-to-url: https://www.ensembl.org/Multi/Search/Results?q={feature}
        consequence:
          plot:
            heatmap:
              color-scheme: category20
              scale: ordinal
        impact:
          plot:
            heatmap:
              scale: ordinal
              domain:
                - HIGH
                - MODERATE
                - LOW
                - MODIFIER
              range:
                - "#ec0000"
                - "#ec5300"
                - "#ec9b00"
                - "#ecca00"

        ?for sample in ["normal", "tumor"]:
          '?f"{sample}: observations"':
            custom-plot:
              data: ?read_file(params.data_observations)
              spec: ?read_file(params.spec_observations)


    ?f"{group}-noncoding":
      desc: ?f"Variants in non-coding regions.\n{config['calling']['fdr-control']['events'][wildcards.event]['desc']}"
      dataset: ?f"{group}-noncoding"
      render-table:
        symbol:
          link-to-url: https://www.ensembl.org/Multi/Search/Results?q={feature}
        consequence:
          plot:
            heatmap:
              color-scheme: category20
              scale: ordinal
        impact:
          plot:
            heatmap:
              scale: ordinal
              domain:
                - HIGH
                - MODERATE
                - LOW
                - MODIFIER
              range:
                - "#ec0000"
                - "#ec5300"
                - "#ec9b00"
                - "#ecca00"

        ?for sample in ["normal", "tumor"]:
          '?f"{sample}: observations"':
            custom-plot:
              data: ?read_file(params.data_observations)
              spec: ?read_file(params.spec_observations)