__use_yte__: true

__definitions__:
  - import os
  - |
    def read_file(path):
        return open(path, 'r').read()

name: Variant publication summaries

default-view: Summaries

datasets:
  Summaries:
    path: ?input.csv
    separator: ","
views:
  Summaries:
    dataset: Summaries
    render-table:
      columns:
        Summary:
          custom-path: ?read_file(input.summary_formatter)
        Variant:
          display-mode: normal
        PMIDs:
          display-mode: normal
          plot:
            pills:
              separator: ";"
              range: ["blue"]
