samples: config/samples.tsv

units: config/units.tsv

igv_report:
  activate: false

ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: saccharomyces_cerevisiae
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 98
  snpeff_release: 86
  # Genome build
  build: R64-1-1

# Estimation of tumor mutational burden.
tmb:
  activate: false
  # Size of the sequenced coding genome for TMB estimation
  # Attention: when doing panel sequencing, set this to the
  # CAPTURED coding genome, not the entire one!
  coding_genome_size: 3.0e7
  # Name of the tumor sample in the scenario.yaml.
  tumor_sample: tumor
  somatic_events:
    - SOMATIC_TUMOR_LOW
    - SOMATIC_TUMOR_MEDIUM
    - SOMATIC_TUMOR_HIGH

calling:
  delly:
    activate: true
  freebayes:
    activate: true
  # See https://varlociraptor.github.io/docs/calling/#generic-variant-calling
  scenario: config/scenario.yaml
  # See http://snpeff.sourceforge.net/SnpSift.html#filter
  filter:
    moderate: "ANN[*].IMPACT has 'MODERATE'"
  fdr-control:
    threshold: 0.05
    events: 
      present:
        varlociraptor: 
          - "PRESENT"
        filter: moderate

annotations:
  dbnsfp:
    activate: false
  vcfs:
    activate: true
    known: refs/variation.vcf.gz
  dgidb:
    activate: true


params:
  cutadapt: ""
  picard:
    MarkDuplicates: ""
  gatk:
    BaseRecalibrator: ""
