samples: config-no-candidate-filtering/samples.tsv

units: config-no-candidate-filtering/units.tsv

ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 17
  # Ensembl species name
  species: saccharomyces_cerevisiae
  # Ensembl release
  release: 100
  # Genome build
  build: R64-1-1

primers:
  trimming:
    activate: false
    primers_fa1: ""
    primers_fa2: ""
    library_length: 0


# Estimation of tumor mutational burden.
mutational_burden:
  activate: false
  events:
    - SOMATIC_TUMOR_LOW
    - SOMATIC_TUMOR_MEDIUM
    - SOMATIC_TUMOR_HIGH

# Plotting of known mutational signatures
mutational_signatures:
  activate: false
  events:
    - some_id

calling:
  delly:
    activate: true
  freebayes:
    activate: true
  # See https://varlociraptor.github.io/docs/calling/#generic-variant-calling
  scenario: config-no-candidate-filtering/scenario.yaml
  # See http://snpeff.sourceforge.net/SnpSift.html#filter
  filter:
    moderate: "ANN['IMPACT'] == 'MODERATE'"
    with_aux:
      aux-files: 
        super_interesting_genes: config-no-candidate-filtering/super_interesting_genes.tsv
      expression: "ANN['SYMBOL'] in AUX['super_interesting_genes']"
  fdr-control:
    threshold: 0.05
    events: 
      present:
        varlociraptor: 
          - "PRESENT"
        filter:
          - moderate
        desc: Moderate variants

tables:
  activate: true
  # vembrane expression to generate the table
  output:
    expression: "INDEX, CHROM, POS, REF, ALT[0], ANN['Consequence'], ANN['IMPACT'], ANN['SYMBOL'], ANN['Feature']"
    genotype: true
    coverage: true
    event_prob: true
  generate_excel: true

annotations:
  vcfs:
    activate: true
    known: resources/variation.vcf.gz
  dgidb:
    activate: false
    datasources:
      - DrugBank
  vep:
    candidate_calls:
      params: ""
      plugins: []
    final_calls:
      params: --everything
      plugins:
        # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
        # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
        - LoFtool


params:
  cutadapt: ""
  picard:
    MarkDuplicates: ""
  gatk:
    BaseRecalibrator: ""
    applyBQSR: ""
  varlociraptor:
    # add extra arguments for varlociraptor call
    # For example, in case of panel data consider to omit certain bias estimations
    # which might be misleading because all reads of an amplicon have the sample start
    # position, strand etc. (--omit-strand-bias, --omit-read-position-bias, 
    # --omit-softclip-bias, --omit-read-orientation-bias).
    call: ""
    # Add extra arguments for varlociraptor preprocess. By default, we limit the depth to 200.
    # Increase this value for panel sequencing!
    preprocess: "--max-depth 200"
  freebayes:
    min_alternate_fraction: 0.05 # Reduce for calling variants with lower VAFs

gene_coverage:
  min_avg_coverage: 5

maf:
  activate: false

report:
  activate: true
  max_read_depth: 250
  stratify:
    activate: false
    by-column: condition
